control_dt: 0.02
# control_dt: 0.01

num_actions: 29


msg_type: "hg"     # "hg" or "go"
imu_type: "pelvis"    # "torso" or "pelvis"

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"


joint2motor_idx: [0, 1, 2, 3, 4, 5, # left leg
                 6, 7, 8, 9, 10, 11, # right leg
                 12, 13, 14, # waist
                 15, 16, 17, 18, 19, 20, 21, # left arm
                 22, 23, 24, 25, 26, 27, 28 # right arm
                 ]

kps: [100, 100, 100, 150, 40, 40, # leg
      100, 100, 100, 150, 40, 40, # leg
      150, 150, 150, # waist
    40, 40, 40, 40, 20, 20, 20, # arm
    40, 40, 40, 40, 20, 20, 20] # arm

kds: [2, 2, 2, 4, 2, 2, # leg   
      2, 2, 2, 4, 2, 2, # leg
      4, 4, 4, # waist
      5, 5, 5, 5, 1, 1, 1, # arm
      5, 5, 5, 5, 1, 1, 1] # arm

# kps: [40.17923847, 99.09842778, 40.17923847, 99.09842778, 28.5012462, 28.5012462,
#       40.17923847, 99.09842778, 40.17923847, 99.09842778, 28.5012462, 28.5012462,
#       40.17923847, 28.5012462, 28.5012462,
#       14.2506231, 14.2506231, 14.2506231, 14.2506231, 14.2506231, 16.77832748, 16.77832748,
#       14.2506231, 14.2506231, 14.2506231, 14.2506231, 14.2506231, 16.77832748, 16.77832748]
# kds: [2.55788977, 6.30880185, 2.55788977, 6.30880185, 1.81444569, 1.81444569,
#       2.55788977, 6.30880185, 2.55788977, 6.30880185, 1.81444569, 1.81444569,
#       2.55788977, 1.81444569, 1.81444569,
#       0.90722284, 0.90722284, 0.90722284, 0.90722284, 0.90722284, 1.0681415, 1.0681415,
#       0.90722284, 0.90722284, 0.90722284, 0.90722284, 0.90722284, 1.0681415, 1.0681415 ]

default_angles: [-0.2, 0.0, 0.0, 0.4, -0.2, 0.0,
                -0.2, 0.0, 0.0, 0.4, -0.2, 0.0,
                0, 0, 0,
                0, 0.4, 0, 1.2, 0.0, 0.0, 0.0,
                0, -0.4, 0, 1.2, 0.0, 0.0, 0.0
                ]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.5 # full is 0.5

